### PR TITLE
ofAVEngineSoundPlayer Fixes for Crashes  / nil / null / AVEngine fail…

### PR DESCRIPTION
**Pull request by danoli3**
ofAVEngineSoundPlayer Fixes for Crashes  / nil / null / AVEngine failures 

Also changed to Objective C++

(cherry picked from commit 299f3e5c65ae570fe397ecaef0bf5beb64fa27c8)

### CODE REVIEW

**Comment by danoli3** [comment]
@ofTheo

**Comment by ofTheo** [comment]
Thanks @danoli3 - do we want the extra NSLogs you uncommented though? 
If you have any sense of how to get a FFT spectrum out of the engine that would be awesome too! :)

**Comment by danoli3** [comment]
Still a few more things to fix with AudioInteruption events, been fixing
that up tonight! Will push tomorrow !

**Comment by danoli3** [comment]
Added further fixes  based off Apple's Code / Testing and experimentation. 

Handle: RouteChange / InteruptionEvents
- Fix Engine / Restart Engine 
- Fixes Crashes and Hangs due to thread locks due to old use of old AVEngine that system destroys / terminates access to hardware 
- Fixes AVAudioSessionCategory issues

It seemed to auto merge in heads up @ofTheo

**Comment by ofTheo** [comment]
Thanks for working this!  
A good test is to plug in headphones ( or disconnect them ) while music is playing, it should continue the audio through the new device.

**Comment by danoli3** [comment]
So many bugs around that engine state: 

Basically if an alert happened via alarm, phone call, message = could potentially kill the Engine and randomly stall for undefined time, or on older devices > 10 seconds = forced crash due to hang 

All cases have been throughly tested on numerous devices now across iOS 11-16 

This new avaudio engine bypasses the mute button on the device finally so yay

**Comment by danoli3** [comment]
I think there's a few things to clean up I forced Hz. Added checks on stop/play for sounds just in case interruption happened in-between things, as did manage to stress test and kill app a few times like that! 

Using in production now and tested daily with those fixes and it's going great

**Comment by ofTheo** [comment]
Wow - awesome!! Thanks man! 
That sounds really promising. 🤘

As soon as you think its ready let me know and we can use this branch or yours to PR into OF

**Pull request merged**
